baseURL = "https://eloquent-banach-9e11fe.netlify.app/"
languageCode = "ja"
title = "klim0824.log()"
theme = "mainroad"
paginate = "10" # Number of posts per page
hasCJKLanguage = true # 中国語・日本語・韓国語の単語カウントを有効にする
summaryLength = 100 # サマリーの長さの単語数

[Author] # Used in authorbox
  name = "klim0824"
  bio = "フロントエンドエンジニアを目指すマークアップエンジニア兼バックエンドエンジニア見習いによるブログ"
  avatar = "img/klim0824.jpg"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "フロントエンドエンジニアを目指すマークアップエンジニア兼バックエンドエンジニア見習いによるブログ" # Site description. Used in meta description
  images = ["img/klim0824.jpg"]
  copyright = "klim0824" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = false # Enable MathJax
#   mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
#   mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "darkslateblue" # Override highlight color
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

[Params.logo]
  image = "img/klim0824.jpg" # Logo image. Path relative to "static"
  title = "klim0824.log()" # Logo title, otherwise will use site title
  subtitle = "" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "klim0824"
  twitter = "klim08241"
  instagram = "klim0824"
  github = "klim0824"
  email = "klim0824@live.jp"
#   linkedin = "klim0824"
#   telegram = "klim0824"
#   gitlab = "klim0824"
#   bitbucket = "klim0824"

# Custom social links
# [[Params.widgets.social.custom]]
#   title = "Youtube"
#   url = "https://youtube.com/user/username"
#   icon = "youtube.svg" # Optional. Path relative to "layouts/partials"

# [[Params.widgets.social.custom]]
#   title = "My Home Page"
#   url = "http://example.com"